### ISSUE TITLE
(application.properties was not found. Are you sure that your folder in hostsettings.json 

### ISSUE THREAD

**Issue by darionstj** [mehtadone/PTFeeder#107]
pt feeder not finding application properties

bash: cd: /Users/darion/Desktop/pt-feeder-v0: No such file or directory
darions-MacBook-Pro:~ d$ cd /Users/d/Desktop/pt-feeder-v0 
darions-MacBook-Pro:pt-feeder-v0 darion$ dotnet pt-feeder.dll
[18:24:52 INF] Starting PT Feeder - version: 1.3.4
[18:24:52 INF] Massive thanks to Elroy and team for Profit Trailer. https://github.com/taniman/profit-trailer
[18:24:52 INF] Running from /Users/d/Desktop/pt-feeder-v0
[18:24:52 INF] Checking for license information
[18:24:52 FTL] An error occurred starting the application
System.AggregateException: One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (application.properties was not found. Are you sure that your folder in hostsettings.json is a PT install? The file that PTF is looking in is /Users/darion/Downloads/bot/application.properties))) ---> System.AggregateException: One or more errors occurred. (One or more errors occurred. (application.properties was not found. Are you sure that your folder in hostsettings.json is a PT install? The file that PTF is looking in is /Users/darion/Downloads/bot/application.properties)) ---> System.AggregateException: One or more errors occurred. (application.properties was not found. Are you sure that your folder in hostsettings.json is a PT install? The file that PTF is looking in is /Users/darion/Downloads/bot/application.properties) ---> ptfeeder.exceptions.SetupException: application.properties was not found. Are you sure that your folder in hostsettings.json is a PT install? The file that PTF is looking in is /Users/darion/Downloads/bot/application.properties
   at Services.services.StartupService.(String )
   at Services.services.StartupService.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.services.StartupService..MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at pt_feeder.Startup.OnStarting() in C:\projects\profittrailer-config-generator\pt-feeder\Startup.cs:line 153
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at Microsoft.AspNetCore.Hosting.Internal.ApplicationLifetime.ExecuteHandlers(CancellationTokenSource cancel)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Hosting.Internal.ApplicationLifetime.ExecuteHandlers(CancellationTokenSource cancel)
   at Microsoft.AspNetCore.Hosting.Internal.ApplicationLifetime.NotifyStarted()
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (One or more errors occurred. (application.properties was not found. Are you sure that your folder in hostsettings.json is a PT install? The file that PTF is looking in is /Users/darion/Downloads/bot/application.properties)) ---> System.AggregateException: One or more errors occurred. (application.properties was not found. Are you sure that your folder in hostsettings.json is a PT install? The file that PTF is looking in is /Users/darion/Downloads/bot/application.properties) ---> ptfeeder.exceptions.SetupException: application.properties was not found. Are you sure that your folder in hostsettings.json is a PT install? The file that PTF is looking in is /Users/darion/Downloads/bot/application.properties
   at Services.services.StartupService.(String )
   at Services.services.StartupService.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.services.StartupService..MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at pt_feeder.Startup.OnStarting() in C:\projects\profittrailer-config-generator\pt-feeder\Startup.cs:line 153
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at Microsoft.AspNetCore.Hosting.Internal.ApplicationLifetime.ExecuteHandlers(CancellationTokenSource cancel)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (application.properties was not found. Are you sure that your folder in hostsettings.json is a PT install? The file that PTF is looking in is /Users/darion/Downloads/bot/application.properties) ---> ptfeeder.exceptions.SetupException: application.properties was not found. Are you sure that your folder in hostsettings.json is a PT install? The file that PTF is looking in is /Users/darion/Downloads/bot/application.properties
   at Services.services.StartupService.(String )
   at Services.services.StartupService.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.services.StartupService..MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at pt_feeder.Startup.OnStarting() in C:\projects\profittrailer-config-generator\pt-feeder\Startup.cs:line 153
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
---> (Inner Exception #0) ptfeeder.exceptions.SetupException: application.properties was not found. Are you sure that your folder in hostsettings.json is a PT install? The file that PTF is looking in is /Users/darion/Downloads/bot/application.properties
   at Services.services.StartupService.(String )
   at Services.services.StartupService.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.services.StartupService..MoveNext()<---
<---
<---
Hosting environment: Production
Content root path: /Users/d/Desktop/pt-feeder-v0
Now listening on: http://localhost:8083
Application started. Press Ctrl+C to shut down.

**Comment by mehtadone** [comment]
Are you sure PT is installed in /Users/darion/Downloads/bot/application.properties)?

**Comment by darionstj** [comment]
yea i found the problem i had moved the pt folder to desktop without realising  thats y it was saying it couldn't locate it in downloads
