### ISSUE TITLE
feeder hang 2 times during binance heavy load, Unhandled Exception

### ISSUE THREAD

**Issue by determo13** [mehtadone/PTFeeder#129]
going back to more stable version, this is exception below happens 2 times.

Unhandled Exception: System.Net.Http.HttpRequestException: An error occurred whi
le sending the request. ---> System.Net.Http.WinHttpException: A connection with
 the server could not be established
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAw
aiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Binance.Api.BinanceHttpClient.<RequestAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Binance.Api.BinanceApi.<Get24HourStatisticsAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at services.services.BinanceWebsocketService.Struct11.MoveNext()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action ac
tion, Boolean allowInlining, Task& currentTask)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by mehtadone** [comment]
See https://support.binance.com/hc/en-us/articles/360000713851

**Comment by determo13** [comment]
yeah but that doesn't mean it should exit with exception is it? if connections drops same thing happens...

**Comment by mehtadone** [comment]
@determo13 can you attach your full log file?

**Comment by determo13** [comment]
Sorry mate I've removed it and using old version now, you can simulate error by running it and then disabling internet connection.

**Comment by mehtadone** [comment]
OK, guessing your Linux and not Windows with a recycling bin?

**Comment by determo13** [comment]
Hi just done another test, here is the log file:

[PTFeeder-20180208.log](https://github.com/mehtadone/PTFeeder/files/1706805/PTFeeder-20180208.log)

**Comment by mehtadone** [comment]
Fixed in 1.6
