### ISSUE TITLE
My Feeder not connect to binance after the restart

### ISSUE THREAD

**Issue by ra666666666** [mehtadone/PTFeeder#132]
The feeder have an error:

---> (Inner Exception #0) Services.serv
nect to Binance. Has your firewall not
e down? Error: A task was canceled.
   at Services.services.ExchangeService
--- End of stack trace from previous lo
   at System.Runtime.ExceptionServices.
   at System.Runtime.CompilerServices.T
ification(Task task)

how can I do?

**Comment by dmalcolm** [comment]
Here is same type of info with debug turned on.

[06:33:24 DBG] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Binance.Api.BinanceHttpClient.<RequestAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Binance.Api.BinanceApi.<GetTimestampAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Binance.Api.BinanceApiExtensions.<GetTimeAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at services.services.ExchangeService. .MoveNext()
[06:33:24 FTL] Could not connect to Binance. Has your firewall not got an exception for PT Feeder? Is binance down? Error: A task was canceled.
Application is shutting down...

**Comment by zapedge** [comment]
they suffer ddos attack on the main address binance.com,
if we hat the opportunuty to select a different server this issue could be solved.
https://twitter.com/cz_binance/status/961888554224726017
us and kr are up and running

**Comment by MJMokhtari** [comment]
Profit trailer passed this issue! If PTF can act as same as PT in reaching to domains, It will never again come to this error :) Now I just wait for Binance. But developers can fix this issue in future release, I hope.

**Comment by serpentoso** [comment]
Same issue here

**Comment by kamillasecki** [comment]
is there any easy way to change the page from binance.com to us.binance.com?

**Comment by mehtadone** [comment]
@kamillasecki Check on the PTF discord. There is a temporary fix

**Comment by yyyc514** [comment]
Please provide a way to specify the URL.  Binding to a DIFFERENT IP address in your hosts file is a BAD idea... those IPs are all temporarily assigned and dynamically dispatched at Cloudflare... they are subject to change - that's what DNS is for.

The software should have a config setting to let you specify which country specific hostname it uses.

**Comment by mehtadone** [comment]
@yyyc514 Totally agree that changing your hosts is a bad idea. But that is all we got at the moment until binance comes back online properly in all regions. The best solution is to wait.

 I will add the option to change the endpoint in PTF but this isn't something we can add straight way.

**Comment by mehtadone** [comment]
Closing this as a duplicate: https://github.com/mehtadone/PTFeeder/issues/134
