### ISSUE TITLE
Getting This error after binance is back up

### ISSUE THREAD

**Issue by junoonis** [mehtadone/PTFeeder#135]
No settings were change either on PT Feeder or PT, after bianance came back up, PT is running fine but I am getting this error on PT FEEDER

`2018-02-09 09:54:58.348 -05:00 [Fatal] An error occurred starting the application
System.AggregateException: One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (Could not connect to Binance. Has your firewall not got an exception for PT Feeder? Is binance down? Error: A task was canceled.))) ---> System.AggregateException: One or more errors occurred. (One or more errors occurred. (Could not connect to Binance. Has your firewall not got an exception for PT Feeder? Is binance down? Error: A task was canceled.)) ---> System.AggregateException: One or more errors occurred. (Could not connect to Binance. Has your firewall not got an exception for PT Feeder? Is binance down? Error: A task was canceled.) ---> Services.services.ConnectivityException: Could not connect to Binance. Has your firewall not got an exception for PT Feeder? Is binance down? Error: A task was canceled.
   at Services.services.ExchangeService. .MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.services.StartupService..MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at pt_feeder.Startup.OnStarting() in C:\projects\profittrailer-config-generator\pt-feeder\Startup.cs:line 153
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)`

**Comment by mehtadone** [comment]
Please see the other existing issues and the discord for a temporary work around https://discord.gg/EKdMG
