### ISSUE TITLE
first run after installing on Pi from GG

### ISSUE THREAD

**Issue by pjfj55** [mehtadone/PTFeeder#175]
at Services.services.StartupService.(String )
   at Services.services.StartupService.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.services.StartupService..MoveNext()<---

have right key registered, Trailer running fine, gone back over all settings, any ideas please

**Comment by mehtadone** [comment]
I need to see the full log file. Can you attach it here?

**Comment by GLock-PPC** [comment]
after an upgrade on my system same isssue (linux not rasppi)

Unhandled Exception: System.InvalidOperationException: The terminfo database is invalid.
   at System.TermInfo.Database..ctor(String term, Byte[] data)
   at System.TermInfo.Database.ReadDatabase(String term, String directoryPath)
   at System.TermInfo.Database.ReadDatabase(String term)
   at System.TermInfo.Database.ReadActiveDatabase()
   at System.ConsolePal.TerminalFormatStrings.<>c.<.cctor>b__27_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.CreateValue()
   at System.ConsolePal.WriteResetColorString()
   at System.ConsolePal.RefreshColors(ConsoleColor& toChange, ConsoleColor value)
   at Serilog.Sinks.SystemConsole.Themes.SystemConsoleTheme.Set(TextWriter output, ConsoleThemeStyle style)
   at Serilog.Sinks.SystemConsole.Themes.ConsoleTheme.Apply(TextWriter output, ConsoleThemeStyle style, Int32& invisibleCharacterCount)
   at Serilog.Sinks.SystemConsole.Output.TextTokenRenderer.Render(LogEvent logEvent, TextWriter output)
   at Serilog.Sinks.SystemConsole.Output.OutputTemplateRenderer.Format(LogEvent logEvent, TextWriter output)
   at Serilog.Sinks.SystemConsole.ConsoleSink.Emit(LogEvent logEvent)
   at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent)
Aborted (core dumped)

**Comment by pjfj55** [comment]
Hi, 
Sorry had to go out last night, got all day to sort now, that was the result from the very first opening, I wiped card and reinstalled but the same issue, I double slashed the address for feeder as i was running on windows, so i will go back in now and take them out as i watched the CG video and realized that was a windows only issue ( I'm 62, I'm allowed to be a dumb Hommer!)

**Comment by pjfj55** [comment]
took out the double slash, no change

**Comment by pjfj55** [comment]
going to revisit the wiki for a lot of reading

**Comment by mehtadone** [comment]
@Gclock-ppc unfortunately not much I can do about that issue. It looks like it's caused by a new version on ncurse. If you can downgrade that, it seems to fix the problem

https://github.com/dotnet/corefhttps://github.com/dotnet/corefx/issues/26966x/issues/26966

**Comment by pjfj55** [comment]
got a 404 on the link

**Comment by mehtadone** [comment]
@pjfj55 this was for @Gclock-ppc issue. I think you mentioned that yours is fixed right?

**Comment by mehtadone** [comment]
Ahh no its not. Can you attach your full log file? @pjfj55

**Comment by pjfj55** [comment]
just getting it from pi (School day)

**Comment by pjfj55** [comment]
[PTFeeder-20180109.log](https://github.com/mehtadone/PTFeeder/files/1734624/PTFeeder-20180109.log)

**Comment by pjfj55** [comment]
thats the only feeder log

**Comment by pjfj55** [comment]
I know its me, just read it and I see what it says, I think I just need the board rubber to hit me!

**Comment by pjfj55** [comment]
in the pi feeder log its saying go to here:
#! /bin/sh -
cd /home/pi/ProfitFeeder/logs
fn=$(ls -t | head -n1)
tail -f -- "$fn" 

but there is a "desktop" missing?
I'll try!

**Comment by pjfj55** [comment]
didn't work!

**Comment by mehtadone** [comment]
Repoen if this is still an issue
