### ISSUE TITLE
Unhandled Exception: System.InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by determo13** [mehtadone/PTFeeder#209]
Again same issue below. It's not happening in pt-feeder-v1.3.4.236.....
worked for couple hours and then exit with exception.... 

Unhandled Exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at services.services.BaseCoinPriceChangeService.Struct4.MoveNext()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Abort trap: 6

**Comment by mehtadone** [comment]
This normally happens when the time on the machine goes out of sync with the actual time and we end up querying the exchange for prices in the future. The exchange tells us to shove it and sends back nothing. Can you trying syncing your time? If you are windows, you can try: https://github.com/mehtadone/PTFeeder/wiki/Common-errors#3-sequence-contains-no-element--could-not-get-btc-price-change-from-all-exchanges-returning-a-massive-value-so-you-end-up-in-superbear-error

**Comment by mehtadone** [comment]
PS. Reopen if still an issue
