### ISSUE TITLE
Object reference not set to an instance of an object. error on startup

### ISSUE THREAD

**Issue by mrulke** [mehtadone/PTFeeder#23]
getting this error on start up then everything goes into watch mode.
here is a screen shot 
![image](https://user-images.githubusercontent.com/11845028/34645741-4df4d1d8-f3a9-11e7-95c5-7b85ae172638.png)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.)) ---> System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Services.services.StartupService.(String )
   at Services.services.StartupService.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.services.StartupService..MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at pt_feeder.Startup.OnStarting() in C:\projects\profittrailer-config-generator\pt-feeder\Startup.cs:line 163
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at Microsoft.AspNetCore.Hosting.Internal.ApplicationLifetime.ExecuteHandlers(CancellationTokenSource cancel)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Services.services.StartupService.(String )
   at Services.services.StartupService.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.services.StartupService..MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at pt_feeder.Startup.OnStarting() in C:\projects\profittrailer-config-generator\pt-feeder\Startup.cs:line 163
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Services.services.StartupService.(String )
   at Services.services.StartupService.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.services.StartupService..MoveNext()<---
<---
<---
Hosting environment: Production
Content root path: C:\Users\#####\Desktop\Feeder
Now listening on: http://localhost:8083
Application started. Press Ctrl+C to shut down.

**Comment by mrulke** [comment]
Looks like an API Key issue. but it is not picking it up even after adding it to the Telegram bot

**Comment by mehtadone** [comment]
No, thats not an api issue. Try running with the default settings first, just editing hostsettings.json. It looks like something is missing from your appsettings.json.

**Comment by mehtadone** [comment]
Reopen if needed
