### ISSUE TITLE
PT Feeder running problem

### ISSUE THREAD

**Issue by a-mashaly** [mehtadone/PTFeeder#312]
I just setup the pre-installed windows vps service and PT is working fine. Feeder won't start and keeps giving me the following error. (since the upgrade as it was working fine on a local computer beforeupgrading and using vps service). PLEASE HELP?

C:\Users\Administrator\Desktop\pt-feeder>dotnet C:\Users\Administrator\Desktop\pt-feeder\pt-feeder.dll
[21:58:30 INF] Starting PT Feeder
[21:58:30 INF] Version: 1.5.0.670
[21:58:30 INF] Massive thanks to Elroy and team for Profit Trailer.
[21:58:30 INF] https://github.com/taniman/profit-trailer
[21:58:30 INF] Running from C:\Users\Administrator\Desktop\pt-feeder
[21:58:31 INF] Detected Profit Trailer Version 2
[21:58:31 DBG] Ping Profit Trailer endpoint https:\localhost:8081
[21:58:31 DBG] Error whilst trying PT endpoint https:\localhost:8081/settingsapi/config/list?license=*********************************
[21:58:31 ERR] Error occured whilst sending to PT settings api: System.InvalidOperationException: An invalid request URI
 was provided. The request URI must either be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, Cancellati
onToken cancellationToken)
   at?.MoveNext()
Hosting environment: Production
Content root path: C:\Users\Administrator\Desktop\pt-feeder
Now listening on: http://localhost:5001
Application started. Press Ctrl+C to shut down.
Application is shutting down...
[21:58:39 INF] Changes have been saved in database

**Comment by mehtadone** [comment]
You ProfitTrailerEndpoint1 needs to be `https://localhost:8081`

**Comment by stefi01** [comment]
heres mine.  
"ProfitTrailerApiEndPoint1": "https://localhost:8081",    deffinatly says 8081
but when i run it gives an error 

Content root path: C:\Users\Administrator\Desktop\ProfitTrailer_2.0\pt-feeder
Now listening on: http://localhost:5001                                   THIS IS DEFINATLY NOT 8081
Application started. Press Ctrl+C to shut down.

**Comment by nric** [comment]
I also think this problem is real.  I get: 

dotnet pt-feeder.dll
[19:10:56 INF] Starting PT Feeder
[19:10:56 INF] Version: 1.5.1.685
[19:10:56 INF] Massive thanks to Elroy and team for Profit Trailer.
[19:10:56 INF] https://github.com/taniman/profit-trailer
[19:10:56 INF] Running from C:\Users\nric\Desktop\PT Feeder 2 Binance ETH
Hosting environment: Production
Content root path: C:\Users\nric\Desktop\PT Feeder 2 Binance ETH
Now listening on: http://localhost:5001
Application started. Press Ctrl+C to shut down.
[19:10:59 ERR] Error occured whilst sending to PT settings api: System.Net.Http.
HttpRequestException: An error occurred while sending the request. ---> System.N
et.Http.WinHttpException: Es ist ein Sicherheitsfehler aufgetreten
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAw
aiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at ♠?.MoveNext()

**Comment by mehtadone** [comment]
Try changing your ProfitTrailerEndPoint1 to http

**Comment by nric** [comment]
that worked, thanks a lot! Keep up the great work with ptf.
