### ISSUE TITLE
[SUGGESTION] Change the "ProfitTrailerApiEndPoint1" example at hostsettings.json

### ISSUE THREAD

**Issue by ingmvillegas** [mehtadone/PTFeeder#325]
The text that explains "// this is where the api is to be found from PT to save your settings. For example, https://localhost:8081"

Should be replaced for "// this is where the api is to be found from PT to save your settings. For example, http://localhost:8081"

The http should be used instead of https, It could get an error like this:

Error occured whilst sending to PT settings api: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A security error occurred
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at  ?.MoveNext()

**Comment by zwarbo** [comment]
+ vote for this small change of text in the comment field. It's catching lots of people out.

**Comment by Yoda2019** [comment]
+1 fixed my problems
