### ISSUE TITLE
Poloniex market summaries request error Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value

### ISSUE THREAD

**Issue by Vladdy1976** [mehtadone/PTFeeder#348]
Cannot get this working on Poloniex - guessing something wrong with the json payload from poloniex. 

I get a detailed error using versoins 1.8.3.1628 to 1.8.5.1623. 

[11:28:12 INF] Starting PT Feeder Version: 1.8.5.1623
[11:28:12 INF] DotNet version: 4.0.30319.42000
[11:28:12 INF] Massive thanks to Elroy and team for ProfitTrailer.
[11:28:12 INF] Running from F:\Crypto\ProfitTrailer\pt-feeder
Hosting environment: Production
Content root path: F:\Crypto\ProfitTrailer\pt-feeder
Now listening on: http://localhost:5001
Application started. Press Ctrl+C to shut down.
[11:28:19 INF] Running PT Version 2.4.40
[11:28:22 INF] Loading initial candles from Poloniex
[11:28:22 ERR] Poloniex market summaries request error Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'BTC_BTS', line 1, position 12.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Exchanges.Extensions.HttpContentExtensions.Get[T](HttpContent httpContent)
   at Exchanges.Implementations.ProfitTrailer.ApiClient.ProfitTrailerApi.GetMarketSummaries() http://localhost:8081/private?command=returnTicker&token=

**Comment by Vladdy1976** [comment]
The previous error was for the previous versions. This is the message from 1.8.6.1624


F:\Crypto\ProfitTrailer\pt-feeder>dotnet pt-feeder.dll
[11:41:49 INF] Starting PT Feeder Version: 1.8.6.1624
[11:41:49 INF] DotNet version: 4.0.30319.42000
[11:41:49 INF] Massive thanks to Elroy and team for ProfitTrailer.
[11:41:49 INF] Running from F:\Crypto\ProfitTrailer\pt-feeder
Hosting environment: Production
Content root path: F:\Crypto\ProfitTrailer\pt-feeder
Now listening on: http://localhost:5001
Application started. Press Ctrl+C to shut down.
[11:41:56 INF] Running PT Version 2.4.40
[11:41:59 INF] Loading initial candles from Poloniex
[11:42:00 INF] The required size of the candles: 5m
[11:42:00 INF] 0 out of 52 pairs queried
[11:42:15 INF] 25 out of 52 pairs queried
[11:42:30 INF] 50 out of 52 pairs queried
[11:42:31 INF] 52 out of 52 pairs queried
[11:42:31 INF] Startup complete.
[11:42:31 INF] Will generate pairs file on next run
[11:42:31 INF] Scheduling market conditions to be checked every 2 minutes
[11:42:31 WRN] Could not calculate VWAP. Not enough coins
[11:42:31 WRN] Could not calculate VWAP. Not enough coins
[11:42:31 WRN] Could not calculate VWAP. Not enough coins
[11:42:32 INF]
[11:42:32 INF] Time trend (15) from Wed, 30 Dec 2020 11:27:32 GMT
[11:42:32 INF] Time trend (60) from Wed, 30 Dec 2020 10:42:32 GMT
[11:42:32 INF] Time trend (1440) from Tue, 29 Dec 2020 11:42:32 GMT
[11:42:32 INF]
[11:42:32 INF] USDT_BTC current price: 0
[11:42:32 INF] USDT_BTC change (15, 60, 1440): 1.79769313486232E+308%, 1.79769313486232E+308%, 1.79769313486232E+308%
[11:42:32 INF]
[11:42:32 INF] TopCoinsAverageShortEma (16 candles, 5m): 0
[11:42:32 INF] TopCoinsAverageLongEma (20 candles, 5m): 0
[11:42:32 INF]
[11:42:32 INF] Measure Times: 15, 60, 1440
[11:42:32 INF]
[11:42:32 INF] Top coins change: NaN%, NaN%, NaN%
[11:42:32 INF] Top coins ATRP average: NaN%, NaN%, NaN%
[11:42:32 INF] Top coins VWAP change: NaN%, NaN%, NaN%
[11:42:32 INF]
[11:42:32 WRN] Could not work out which market condition to use. Using the last one

**Comment by mehtadone** [comment]
This normally happens when PT hasn't collected the data yet. I would suggest starting PT first, waiting about 15 mins and then starting Feeder.
