### ISSUE TITLE
PT-Feeder unable to update

### ISSUE THREAD

**Issue by Fez3** [mehtadone/PTFeeder#36]
Does anyone know how to fix this? I can't figure out where the problem is

[Warning] Bollox. Something went wrong getting config for BTC-EOS. Will use default config
 System.NullReferenceException: Object reference not set to an instance of an object.
   at Services.services.OverrideService.SanitizeProperties(Pair pair)
   at ptfeeder.ProfitTrailer.<PairSpecificConfig>d__14.MoveNext() in C:\projects\profittrailer-config-generator\pt-feeder\ProfitTrailer.cs:line 239

**Comment by mehtadone** [comment]
This is normally one of these reasons: 

Exchange is not returning data - API ban, api down. 
Time/timezone in correct.
