### ISSUE TITLE
Need better error handling of json config scripts

### ISSUE THREAD

**Issue by nibarulabs** [mehtadone/PTFeeder#38]
Right now when there's an error in either of the json configs, PTF just barfs up the stack trace. It would be nice to somehow wrap this exception and possibly print out the line number where the error is happening..? I know that can be difficult probably due to the json parser, but it would really help troubleshooting install issues.

Here's the error I see for a appsettings.json file with a bad value (at least I know it's a number!)

```
[14:36:14 INF] Starting PT Feeder (no longer a mouthful)
[14:36:14 INF] Massive thanks to Elroy and team for Profit Trailer. https://github.com/taniman/profit-trailer
[14:36:14 INF] Running from /home/profitbot/bittrex/PT-Feeder/pt-feeder-v1.3.3.208
[14:36:14 ERR] Error in reading general config
[14:36:14 FTL] An error occurred starting the application
System.AggregateException: One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (Failed to convert '' to type 'System.Double'.))) ---> System.AggregateException: One or more errors occurred. (One or more errors occurred. (Failed to convert '' to type 'System.Double'.)) ---> System.AggregateException: One or more errors occurred. (Failed to convert '' to type 'System.Double'.) ---> System.InvalidOperationException: Failed to convert '' to type 'System.Double'. ---> System.Exception:  is not a valid value for Double. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.ComponentModel.DoubleConverter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.TryConvertValue(Type type, String value, Object& result, Exception& error)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance)
   at ptfeeder.services.HotConfigService.BindConfig() in C:\projects\profittrailer-config-generator\pt-feeder\services\HotConfigService.cs:line 34
   at Services.services.StartupService. .MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at pt_feeder.Startup.OnStarting() in C:\projects\profittrailer-config-generator\pt-feeder\Startup.cs:line 150
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at Microsoft.AspNetCore.Hosting.Internal.ApplicationLifetime.ExecuteHandlers(CancellationTokenSource cancel)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Hosting.Internal.ApplicationLifetime.ExecuteHandlers(CancellationTokenSource cancel)
   at Microsoft.AspNetCore.Hosting.Internal.ApplicationLifetime.NotifyStarted()
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (One or more errors occurred. (Failed to convert '' to type 'System.Double'.)) ---> System.AggregateException: One or more errors occurred. (Failed to convert '' to type 'System.Double'.) ---> System.InvalidOperationException: Failed to convert '' to type 'System.Double'. ---> System.Exception:  is not a valid value for Double. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.ComponentModel.DoubleConverter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.TryConvertValue(Type type, String value, Object& result, Exception& error)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance)
   at ptfeeder.services.HotConfigService.BindConfig() in C:\projects\profittrailer-config-generator\pt-feeder\services\HotConfigService.cs:line 34
   at Services.services.StartupService. .MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at pt_feeder.Startup.OnStarting() in C:\projects\profittrailer-config-generator\pt-feeder\Startup.cs:line 150
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at Microsoft.AspNetCore.Hosting.Internal.ApplicationLifetime.ExecuteHandlers(CancellationTokenSource cancel)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (Failed to convert '' to type 'System.Double'.) ---> System.InvalidOperationException: Failed to convert '' to type 'System.Double'. ---> System.Exception:  is not a valid value for Double. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.ComponentModel.DoubleConverter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.TryConvertValue(Type type, String value, Object& result, Exception& error)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance)
   at ptfeeder.services.HotConfigService.BindConfig() in C:\projects\profittrailer-config-generator\pt-feeder\services\HotConfigService.cs:line 34
   at Services.services.StartupService. .MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at pt_feeder.Startup.OnStarting() in C:\projects\profittrailer-config-generator\pt-feeder\Startup.cs:line 150
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
---> (Inner Exception #0) System.InvalidOperationException: Failed to convert '' to type 'System.Double'. ---> System.Exception:  is not a valid value for Double. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.ComponentModel.DoubleConverter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.TryConvertValue(Type type, String value, Object& result, Exception& error)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance)
   at ptfeeder.services.HotConfigService.BindConfig() in C:\projects\profittrailer-config-generator\pt-feeder\services\HotConfigService.cs:line 34
   at Services.services.StartupService. .MoveNext()<---
<---
<---
Hosting environment: Production
Content root path: /home/profitbot/bittrex/PT-Feeder/pt-feeder-v1.3.3.208
Now listening on: http://localhost:5001
Application started. Press Ctrl+C to shut down.
^CApplication is shutting down...
```

**Comment by nibarulabs** [comment]
Found the issue:

```"MinBuyValue": ""```

So, could not convert null to a Double/Number..

I'll leave this up since we'll still need some kind of sanity check on these configs. 👍

**Comment by mehtadone** [comment]
Error message clearer in next version
