### ISSUE TITLE
Error validating API key

### ISSUE THREAD

**Issue by kade119** [mehtadone/PTFeeder#43]
PT runs fine stand alone, PT feeder is is not able to validate the default API key after registering with telegram, actually it told my key was already registered.

Log error

```
2018-01-10 23:50:40.632 -06:00 [Information] Running from C:\Users\myname\Documents\pt-feeder-v1.3.3.208
2018-01-10 23:50:40.651 -06:00 [Information] Checking for license information
2018-01-10 23:50:40.654 -06:00 [Information] Polo setup detected. Will create .properties files in C:\Users\myname\Documents\ProfitTrailer\trading
2018-01-10 23:50:41.900 -06:00 [Fatal] An error occurred starting the application
System.AggregateException: One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One of your api keys is not valid. Have you added your default_key to your license using the telegram bot @ptfeederlicensebot ?))) ---> System.AggregateException: One or more errors occurred. (One or more errors occurred. (One of your api keys is not valid. Have you added your default_key to your license using the telegram bot @ptfeederlicensebot ?)) ---> System.AggregateException: One or more errors occurred. (One of your api keys is not valid. Have you added your default_key to your license using the telegram bot @ptfeederlicensebot ?) ---> Services.services.InvalidLicenseException: One of your api keys is not valid. Have you added your default_key to your license using the telegram bot @ptfeederlicensebot ?
   at Services.services.StartupService..MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.services.StartupService. .MoveNext()
   --- End of inner exception stack trace ---

```

**Comment by kade119** [comment]
This has been resolved via discord, thanks guys!
